### ISSUE TITLE
完成 RadenDh5/A0001.razor 三個TABS裡的顯示欄位如同 WES

### ISSUE THREAD

**Issue by twoutlook** [twoutlook/TH001-ISSUE-TRACKER#1]
目的：正式量產前的試Run, 先熟悉開發模式
估工：1 小時
要點：

- 理解 RadzenTabs 的格式寫法, https://blazor.radzen.com/tabs
- 理解 Blazor, https://dotnet.microsoft.com/learn/aspnet/blazor-tutorial/modify 
  - @foreach (var x in UserMsts)
  - IEnumerable<RadzenDh5.DHModels.UserMst> UserMsts;
  - UserMsts = db.UserMst.OrderBy(x => x.UserId);

![65cd019b9aabb7402b05b34fcd5f4c5](https://user-images.githubusercontent.com/16488072/113465254-3400af80-9465-11eb-95d9-0f5dd1366ec7.png)

**Comment by twoutlook** [comment]
![122087ff9231cfbcae92c57be426ecc](https://user-images.githubusercontent.com/16488072/113498047-00dd1f80-953c-11eb-8adf-8afcb096e44d.png)
https://github.com/twoutlook/TH001-ISSUE-TRACKER/blob/main/README.md
請按上述範例 Closed 
Thanks!

**Comment by qamartw** [comment]
已完成
實際使用工時: 1.25 小時
https://github.com/dreamtek002/th001/commit/545544c149f54975bf74ff3458177129dd63dedd
心得: 確定如何使用Radzen Blazor Tabs component.一模一樣的 ISSUE, 重做約30分鐘可完成, 包括push source code and deploy
